* Nix starter kit

** Provisioning a fresh system

- Install the [[https://nixos.org][Nix package manager]] and enable Flakes
- FIXME: bootstrapping!
- On the target system, use the provided template to create an initial
  home-manager configuration with batteries included:

#+begin_src shell
mkdir -p ~/.config
nix flake new --template github:active-group/nix-starter-kit ~/.config/home-manager
#+end_src

- To configure "modules" like Emacs, =zsh=, or others, check the README files in
  their respective subdirectories in this repository
- If you wish to use LaTeX with batteries included, then you need to clone the
  =howto= repository to =~/howto= (or configure the path in your =home.nix= according
  to your checkout path). If you already have a working LaTeX setup, you don't
  need to change anything.

** Usage

*** Adding software

On https://search.nixos.org/packages you can search for packages you'd like to
have available on your system. Add those packages to your =home.nix= in
=home.packages=. Check out [[https://nix-community.github.io/home-manager/][the home-manager manual]] or ask someone if in trouble :)

To "activate" a new configuration, always execute

#+begin_src shell
home-manager switch
#+end_src

*** Out-of-office notifications via =sieve-connect= (FIXME)

The file [[file:sieve/message.template][message.template]] contains a template for the message you wish to be
shown. Create a copy of this file named =message=:

#+begin_src bash
cp ./sieve/message.template ./sieve/message
#+end_src

Now edit it according to your preferences and personal details. To then activate
the notification, execute

#+begin_src bash
./sieve/sieve.sh activate
#+end_src

Note: you will be asked for you IMAP/Sieve username (only) on first use. This is
your mail address, not your LDAP user name.

To deactivate the notifications, execute

#+begin_src bash
./sieve/sieve.sh deactivate
#+end_src

** Keeping things up to date

When asked to update your configuration (usually when something has changed in
the starter kit), do the following:

#+begin_src bash
cd ~/.config/home-manager
nix flake update
home-manager switch
nix run github:active-group/nix-starter-kit#update-daemon
#+end_src

See the note on updating the Mac trampolines in [[file:modules/mac-app-util/README.org::*mac-app-util][README for mac-app-util]].

If you see errors related to "sandbox initialization", you might need to turn
off sandboxing temporarily in =/etc/nix/nix.conf=.

** Updating Nixpkgs (for admins)

#+begin_src bash
cd .../nix-starter-kit
nix flake update
#+end_src

If there's a new Nix version, consider updating the version number in =flake.nix=.
Then =git push=.

# Local Variables:
# fill-column: 80
# End:
