* Nix starter kit

NOTE: This setup has only been tested on macOS (=x86_64-darwin=) so far. If you
need it on any other architecture/OS, talk to Johannes and we'll adapt it
accordingly.

** Provisioning a fresh system

1. Install the [[https://nixos.org][Nix package manager]] on the target
2. Create a "release" tarball locally by running
   ~./create_bootstrapping_tarball.sh~
3. On the target system, extract this archive to ~~/.config/home-manager~, for
   instance:
#+begin_src shell
mkdir -p ~/.config/home-manager
cd ~/.config/home-manager
tar xvf <path/to>/nix-starter-kit.tar.xz
#+end_src
4. ~cp user-settings.nix.template user-settings~
5. ~vi user-settings.nix~ und ausfüllen
6. Run ~./bootstrap.sh~

** Usage

*** Adding software

On https://search.nixos.org/packages you can search for packages you'd like to
have available on your system. Add those packages to your =user-settings.nix= in
the respective list.

To "activate" a new configuration, always execute

#+begin_src shell
home-manager switch
#+end_src

*** Out-of-office notifications via =sieve-connect=

The file [[file:sieve/message][message]] contains a template for the message you wish to be shown. Fill
in your details there before using the script.

To activate the notification, execute

#+begin_src bash
./sieve/sieve.sh activate
#+end_src

Note: you will be asked for you IMAP/Sieve username (only) on first use. This is
your mail address, not your LDAP user name.

To deactivate the notifications, execute

#+begin_src bash
./sieve/sieve.sh deactivate
#+end_src

# Local Variables:
# fill-column: 80
# End:
