* Nix starter kit

NOTE: This setup has only been tested on macOS (=x86_64-darwin=) so far. If you
need it on any other architecture/OS, talk to Johannes and we'll adapt it
accordingly.

** Provisioning a fresh system

1. Install the [[https://nixos.org][Nix package manager]] on the target
2. On the target system, clone this repository to ~~/.config/home-manager~, for
   instance:
#+begin_src shell
mkdir -p ~/.config
git clone https://github.com/active-group/nix-starter-kit ~/.config/home-manager
cd ~/.config/home-manager
#+end_src
4. ~cp user-settings.nix.template user-settings~
5. ~vi user-settings.nix~ und ausfüllen
6. To configure "modules" like Emacs, =zsh=, or others, check the README files in
   their respective subdirectories
7. Run ~./bootstrap.sh~
8. Create or add an SSH key pair, register that with our services etc.
9. At some point, clone the =howto= repository to =~/howto=. This is needed for
   LaTeX support to work properly with AG documents.

** Usage

*** Adding software

On https://search.nixos.org/packages you can search for packages you'd like to
have available on your system. Add those packages to your =user-settings.nix= in
the respective list.

To "activate" a new configuration, always execute

#+begin_src shell
home-manager switch
#+end_src

*** Out-of-office notifications via =sieve-connect=

The file [[file:sieve/message][message]] contains a template for the message you wish to be shown. Fill
in your details there before using the script.

To activate the notification, execute

#+begin_src bash
./sieve/sieve.sh activate
#+end_src

Note: you will be asked for you IMAP/Sieve username (only) on first use. This is
your mail address, not your LDAP user name.

To deactivate the notifications, execute

#+begin_src bash
./sieve/sieve.sh deactivate
#+end_src

** Updating Nixpkgs

Check:

https://github.com/NixOS/nixpkgs/branches

Go to the desired release branch.  =nixpkgsRev= is latest commit of this branch.

If you change the release channel,  update =stateVersion=.

# Local Variables:
# fill-column: 80
# End:
