* Nix starter kit

NOTE: This setup has only been tested on macOS so far. If you
need it on any other architecture/OS, talk to Johannes and we'll adapt it
accordingly.

** Provisioning a fresh system

- Install the [[https://nixos.org][Nix package manager]]
- On the target system, clone /this repository/ to =~/.config/home-manager=, for
   instance:
#+begin_src shell
mkdir -p ~/.config
git clone https://github.com/active-group/nix-starter-kit ~/.config/home-manager
cd ~/.config/home-manager
#+end_src
- ~cp user-settings.nix.template user-settings.nix~
- Edit ~user-settings.nix~
- To configure "modules" like Emacs, =zsh=, or others, check the README files in
   their respective subdirectories
- Run ~./bootstrap.sh~ (this just enables Flakes support for Nix by changing a
  configuration file, and then uses ~home-manager~ to install the first version
  of your system)
- For new people: Create or add an SSH key pair and make sure access to our
  GitLab is working. If you already have one set up, there is nothing for you to
  do.
- If you wish to use LaTeX with batteries included, then you need to clone the
  =howto= repository to =~/howto=. If you already have a working LaTeX setup,
  you don't need to change anything.

** Usage

*** Adding software

On https://search.nixos.org/packages you can search for packages you'd like to
have available on your system. Add those packages to your =user-settings.nix= in
the respective list.

To "activate" a new configuration, always execute

#+begin_src shell
home-manager switch
#+end_src

*** Out-of-office notifications via =sieve-connect=

The file [[file:sieve/message.template][message.template]] contains a template for the message you wish to be
shown. Create a copy of this file named =message=:

#+begin_src bash
cp ./sieve/message.template ./sieve/message
#+end_src

Now edit it according to your preferences and personal details. To then activate
the notification, execute

#+begin_src bash
./sieve/sieve.sh activate
#+end_src

Note: you will be asked for you IMAP/Sieve username (only) on first use. This is
your mail address, not your LDAP user name.

To deactivate the notifications, execute

#+begin_src bash
./sieve/sieve.sh deactivate
#+end_src

** Keeping things up to date

Run this in the shell

#+begin_src bash
cd ~/.config/home-manager
git pull
home-manager switch
#+end_src

** Updating Nixpkgs (for admins)

Check:

https://github.com/NixOS/nixpkgs/branches

Go to the desired release branch.  =nixpkgsRev= is latest commit of this branch.

If you change the release channel,  update =stateVersion=.

# Local Variables:
# fill-column: 80
# End:
