name: ci
on: [ push, workflow_dispatch ]

env:
  NIX_PATH: "nixpkgs=channel:nixos-unstable"

jobs:
  test-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: create user flake from template
        run: nix flake new --template .# /tmp/blub
      - name: build the home configuration
        run: cd /tmp/blub && nix build .#homeConfigurations.sperber.activationPackage -L -j auto
